server:
  port: 8091
spring:
  application:
    name: seata-server
  main:
    web-application-type: none
logging:
  config: classpath:logback-spring.xml
  file:
    path: ${log.home:${user.home}/logs/seata}
  extend:
    logstash-appender:
      # off by default
      enabled: false
      destination: 127.0.0.1:4560
    kafka-appender:
      # off by default
      enabled: false
      bootstrap-servers: 127.0.0.1:9092
      topic: logback_to_logstash
      producer:
        acks: 0
        linger-ms: 1000
        max-block-ms: 0
    metric-appender:
      # off by default
      enabled: false

seata:
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username: ${spring.cloud.nacos.username:}
      password: ${spring.cloud.nacos.password:}
      group: SEATA_GROUP
      namespace: public
      data-id: seata.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      group: SEATA_GROUP
      namespace: public
      cluster: default
      server-addr: 127.0.0.1:8848
      username: ${spring.cloud.nacos.username:}
      password: ${spring.cloud.nacos.password:}
  store:
    # support: file 、 db 、 redis 、 raft
    mode: file
